version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-dev
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - app_shared_network
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-prod
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: npm run start:prod
    networks:
      - app_shared_network
  postgres:
    image: postgres:latest
    container_name: postgres_data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app_shared_network

volumes:
  postgres_data:

networks:
  app_shared_network:
    external: true
